# Generated by Django 4.1.1 on 2022-10-19 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_produit_date_de_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 13, 17, 19, 261686)),
        ),
        migrations.CreateModel(
            name='PanierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.commandes')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='commande',
            field=models.ManyToManyField(through='home.CommandeProduit', to='home.commandes'),
        ),
        migrations.AddField(
            model_name='produit',
            name='panier',
            field=models.ManyToManyField(through='home.PanierProduit', to='home.panier'),
        ),
    ]
