# Generated by Django 4.1.1 on 2022-10-19 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_produit_date_de_stock_panierproduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 13, 18, 48, 770206)),
        ),
    ]
