# Generated by Django 4.1.1 on 2022-10-19 18:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_produit_date_de_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 19, 36, 36, 818573)),
        ),
    ]
