# Generated by Django 4.1.1 on 2022-11-08 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_commandes_prix_total_alter_commandes_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='avis',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='contenu',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 9, 13, 16, 967872)),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 9, 13, 16, 962873)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 9, 13, 16, 967872)),
        ),
    ]
