# Generated by Django 4.1.1 on 2022-11-16 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_commandes_pending_alter_avis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 18, 37, 2, 18428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='avis',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produit'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.commandes'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produit'),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 19, 37, 2, 18428)),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_livraison',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='favoris',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panierproduit',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.panier'),
        ),
        migrations.AlterField(
            model_name='panierproduit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 19, 37, 2, 18428)),
        ),
    ]
