# Generated by Django 4.1.1 on 2022-11-16 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_avis_date_alter_avis_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='username',
        ),
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 18, 51, 26, 263823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 19, 51, 26, 263823)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 19, 51, 26, 263823)),
        ),
    ]
