# Generated by Django 4.1.1 on 2022-11-21 13:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_facture_total_alter_avis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 13, 13, 32, 900421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 14, 13, 32, 895423)),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='source',
            field=models.FileField(null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 14, 13, 32, 895423)),
        ),
    ]
