# Generated by Django 4.1.1 on 2022-12-01 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_avis_date_alter_commandes_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='ship_option',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 18, 10, 46, 643938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 10, 46, 638937)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 10, 46, 638937)),
        ),
    ]
