# Generated by Django 4.1.1 on 2022-12-01 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_commandes_ship_option_alter_avis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 20, 28, 699638, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 20, 20, 28, 689683)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 20, 20, 28, 694675)),
        ),
    ]
