# Generated by Django 4.1.1 on 2022-12-12 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_contact_email_contact_message_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 1, 25, 53, 413008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 1, 25, 53, 412008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 1, 25, 53, 407007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_de_stock',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 1, 25, 53, 408007, tzinfo=datetime.timezone.utc)),
        ),
    ]
